# Build settings
theme: minima

markdown: kramdown
highlighter: rouge
future: true
excerpt_separator: <!--more-->

paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - etc
